### PR TITLE
ContactGroup sync ( labels ) 

### PR DESCRIPTION
**Pull request by Rarder44**
I added the synchronization of the labels (contactGroup).
From first tests it seems to work, if I find errors / bugs I will make another pull request.

### CODE REVIEW

**Comment by mrmattwilkins** [comment]
Thanks Rarder, appreciate this.  Before I merge it, can you remove the debugging printing, and change camel to snake case, just to keep style consistent?  Cheers.

**Comment by Rarder44** [comment]
ok, I set the new prints as vprint (the only vprint in addition to yours that I have left is in Contacts .__ init__ which during the first login displays the name of the account in which to authenticate).
for the camelCase I changed all references except the words contactGroups since the google service is called just like this).

**Comment by mrmattwilkins** [comment]
Thanks Rader44.  Would you be so kind as to put your code comments in English?  Hope that doesn't sound like I'm being a dick, but I only speak English!

**Comment by mrmattwilkins** [comment]
I'm sure it will be better than me translating it!!  Are you Italian?
Thanks, appreciate it.

**Comment by Rarder44** [comment]
Yes 🤌🤌🤌

**Comment by Rarder44** [comment]
translated.
I hope I have not made too many mistakes and have not skipped any comments!

**Pull request merged**
