### PR TITLE
backup implementation

### PR DESCRIPTION
**Pull request by Rarder44**
I started implementing a backup.
at the moment the whole "con" object (containing the contacts of all the accounts) is saved.
I just sketched the "restore.py" file which should allow you to restore your contacts. (TODO)

this code is of "necessity";
I think a more elegant implementation is to export the CSV file before each synchronization (or after a successful synchronization) so that you can restore it directly from the website and re-initialize the accounts.
the problem is that I have not found any API that allow you to download the CSV so I should start mapping the fields by hand.

what do you think?

### CODE REVIEW

**Comment by Rarder44** [comment]
I used the same branch to implement: adding a new account without having to re-initialize everything.
fixed a problem related to the rate limit (I hope).

for backups, I was thinking that they could be kept as I have implemented, and modify the "restore.py" in order to restore contacts and contactGroups as well as backupped.
(if there are sync issues, they will be fixed at the next sync)

**Comment by Rarder44** [comment]
Do NOT rename the variable groupTag (564) into tag

**Comment by Rarder44** [comment]
Hi, I've been using it like this since I've done the pr.
there are a few fixes so for me it's better to merge...
I wrote the comment "Do NOT rename the variable groupTag (564) into tag"
I don't remember why xD but it was definitely something that was used that way...

**Comment by mrmattwilkins** [comment]
Give me a day or two, I'll give it a try first, then merge it in if everything keeps working fine.  I'm assuming it will, you seem to know what you are doing!  But I got this working ages ago, and haven't touched it for a while. Kinda forget how it all works...

**Comment by mrmattwilkins** [comment]
Backup implementation from Luca Pozzi

**Comment by mrmattwilkins** [comment]
Looks to be working fine.  I did make a couple small changes, you had a cp['DEFAULT']['backupdays'] in a few places, I changed to cp['DEFAULT'].get('backupdays', 0) because I didn't have that field in my config file.  Then black did its linting and changed a few cosmetic things.  I liked the _print function, that was neat.

**Comment by Rarder44** [comment]
> you had a cp['DEFAULT']['backupdays'] in a few places, I changed to cp['DEFAULT'].get('backupdays', 0) 
you're right, I forgot to add a config.default / do checks on already existing config files.

> I liked the _print function, that was neat.
Thanks!

**Pull request merged**
