### PR TITLE
small - various modifications

### PR DESCRIPTION
**Pull request by Rarder44**
various modifications:
- portable mode
- display error during the update phase if verbose = true
- "fix" saving the last update date (see comments)
- "fix" multiple birthdays (see comments)

### CODE REVIEW

**Comment by mrmattwilkins** [comment]
Hi Lucca,
Before I merge, could you make a small change please?  Instead of doing the birthday thing in sync.py, can you do the modification in contacts.py around line 202?  You will see I do something similar for gender, and that is really the right place to put this I think.
Cheers
Matt

**Comment by Rarder44** [comment]
done.
sorry I hadn't seen that there was the exact same problem on other fields.

**Review by mrmattwilkins — APPROVED** [review]
All good

**Comment by mrmattwilkins** [comment]
Thanks for tidying it up and summiting the merge request btw

**Comment by mrmattwilkins** [comment]
No worries Luca, looks good now.  It is very hard to dip into someone
else's code and figure it all out.

**Pull request merged**
